[build]
  base = "F:DailyDeeds"
  command = "npm run build:prod"
  publish = "dist/browser"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/json-server"
  status = 200
